In [3]:
import numpy as np
np.array([1,2,3,4,5])
b= np.array([1,2,3,4,5])



In [4]:
np.zeros((4,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
np.full((3,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [6]:
np.arange(10,71,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

In [7]:
np.linspace(10,20,15)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

In [8]:
np.random.rand(15)

array([0.71066969, 0.38851482, 0.74682499, 0.2563956 , 0.41086033,
       0.43360866, 0.40253627, 0.6237451 , 0.1406791 , 0.36574894,
       0.71440103, 0.34958481, 0.77680152, 0.29163448, 0.32275487])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
m=np.arange(0,24)

In [11]:
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
m.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
array=np.random.rand(10)

In [14]:
array

array([0.01862607, 0.40097357, 0.11469196, 0.1228986 , 0.02626838,
       0.7607561 , 0.4314399 , 0.23874929, 0.40097365, 0.37685223])

In [15]:
array.max()

0.7607561040602918

In [16]:
array.min()

0.018626070636598713

In [17]:
merve=np.random.rand(36).reshape((6,6))


In [18]:
merve

array([[0.72531484, 0.67026793, 0.30201779, 0.42558664, 0.19289585,
        0.35021712],
       [0.07613972, 0.37841366, 0.41259203, 0.85175123, 0.68947904,
        0.40764787],
       [0.49570752, 0.75562556, 0.84255228, 0.94589383, 0.57667099,
        0.77685179],
       [0.71675522, 0.27086087, 0.41959471, 0.02813   , 0.88385908,
        0.66419422],
       [0.14228925, 0.49970026, 0.04623245, 0.216392  , 0.31087829,
        0.60528952],
       [0.69274853, 0.97509854, 0.34301251, 0.45120094, 0.64792546,
        0.49348922]])

In [19]:
merve[4:-1]

array([[0.14228925, 0.49970026, 0.04623245, 0.216392  , 0.31087829,
        0.60528952]])

In [20]:
merve[5:,5:]

array([[0.49348922]])

In [21]:
merve[:,3]

array([0.42558664, 0.85175123, 0.94589383, 0.02813   , 0.216392  ,
       0.45120094])

In [23]:
for i in merve.flat:
    print(i)

0.7253148446422891
0.6702679319568939
0.3020177888563881
0.42558664388997447
0.1928958506769558
0.3502171198159335
0.07613971793032248
0.37841365992249165
0.41259203233116637
0.8517512322108298
0.6894790440854752
0.40764787160555005
0.4957075180567333
0.7556255563502069
0.8425522837082182
0.9458938332953641
0.5766709901124233
0.7768517879650653
0.7167552197935025
0.2708608735096809
0.41959470565840085
0.02813000332660065
0.8838590799999547
0.6641942184825482
0.1422892450578821
0.4997002616030156
0.046232451798632446
0.2163920020686172
0.31087828601301715
0.6052895197704895
0.6927485313289534
0.9750985421584406
0.3430125083087131
0.4512009379826789
0.6479254566262678
0.49348922087596614


In [27]:
n=np.random.rand(1)

In [28]:
n

array([0.05885748])

In [29]:
n*5

array([0.2942874])

In [31]:
np.sum(merve)

18.283276771775643

In [32]:
np.std(merve)

0.2554513966923895

In [33]:
np.var(merve)

0.06525541607209252

In [34]:
merve = merve.T

In [35]:
merve

array([[0.72531484, 0.07613972, 0.49570752, 0.71675522, 0.14228925,
        0.69274853],
       [0.67026793, 0.37841366, 0.75562556, 0.27086087, 0.49970026,
        0.97509854],
       [0.30201779, 0.41259203, 0.84255228, 0.41959471, 0.04623245,
        0.34301251],
       [0.42558664, 0.85175123, 0.94589383, 0.02813   , 0.216392  ,
        0.45120094],
       [0.19289585, 0.68947904, 0.57667099, 0.88385908, 0.31087829,
        0.64792546],
       [0.35021712, 0.40764787, 0.77685179, 0.66419422, 0.60528952,
        0.49348922]])